### ISSUE TITLE
ValueError is hard to use

### ISSUE THREAD

**Issue by eolivelli** [datastax/astrapy#126]
I am using AstraPy to perform a lookup.

I am forcing the API to return an error, and I want to take some actions depending on the error.

```python
        try:
            collection.find_one(filter={
                'metadata.chunks': {'$gt': 2}
            })
            pytest.fail("Should have thrown ValueError")
        except ValueError as e:
            # This looks very ugly, but it's the only way to get the error message
            error = json.loads(e.args[0])[1]
            assert error.get("errorCode") == "UNSUPPORTED_FILTER_OPERATION"
```

Currently the ValueError object has no easy way to be manipulated, it contains a string with a JSON that contains a raw error coming from the serve.

# Proposal
Return a better representation of the errors, with some data structure that can be handled by the application

**Comment by hemidactylus** [comment]
Here's an idea: what about an ad-hoc class (subclass of a suitable standard Python exception) representing `an error from the API` (specifically, an error from the API but with http 200, such as unsupported filter, illegal field name, document exists already, etc...).

This would have a field with the JSON representation of the response from the API, for easier usage by the client code.
(@erichare thoughts?)

**Comment by erichare** [comment]
I actually think thats a great idea. It seems like over the last few days this has been a really common problem for people, and I completely understand why. It's much more elegant to actually receive an "error" (i.e., an exception) when something went wrong with the API call. I'd love to actually have that take place at the API level, but until then, I think having an abstraction over these scenarios is very smart.

This is just a toy example, but something along these lines

```python
class APIRequestError(Exception):
    def __init__(self, message):
        super().__init__(message)

class APIRequestHandler:
    def __init__(self, url):
        self.url = url

    def make_request(self):
        try:
            response = httpx.get(self.url)  # TODO: Update with our actual generic utils function
            return self._process_response(response)
        except httpx.RequestError as e:
            raise APIRequestError(f"An error occurred while making the request: {e}")

    def _process_response(self, response: Response):
        if not 200 <= response.status_code < 300:  # TODO: Is this the right range? Any abstractions?
            raise APIRequestError(f"Non-success status code received: {response.status_code}")

        data = response.json()
        if "error" in data:
            raise APIRequestError(f"API returned an error: {data['error']}")

        return data
  ```
