### ISSUE TITLE
Do not log request body at DEBUG level

### ISSUE THREAD

**Issue by mendonk** [datastax/astrapy#147]
Do not log the request body at DEBUG level -  I did an insertMany with 20 documents with vectors and there was much logging. Log at trace if you must. 
In [astrapy/utils.py](https://github.com/datastax/astrapy/blob/master/astrapy/utils.py#L40)
Issue raised for @amorton

**Comment by hemidactylus** [comment]
What I had in mind is to log a "shortened" query, where each `$vector` in the payload is shortened, the rest being left untouched (+ the full vector at trace level).

Let's check this option if you think it's useful, wdyt?
