### ISSUE TITLE
Request: Need methods that support text inputs

### ISSUE THREAD

**Issue by devinbost** [datastax/astrapy#151]
There needs to be an easier way to use this library to run spot tests on data. 
Here's an example scenario that I run into all the time. I want to perform a filter like this:
```
documents = collection.vector_find(
    "example text",
    limit=100,
)
```
without needing to go through all the steps to vectorize, etc.

**Comment by cbornet** [comment]
This seems a bit out of scope of DB driver. I think a framework like LangChain or Llama-Index is more appropriate for that.

**Comment by hemidactylus** [comment]
Closing for now as out of scope (at least until the underlying API implements the "vectorize" operation)
