### ISSUE TITLE
Documentation link is bad

### ISSUE THREAD

**Issue by T-Lind** [datastax/astrapy#195]
The link under "[More information](https://github.com/datastax/astrapy/blob/da549c34319d9ef33ceb2962d4445311b29da70f/README.md#more-information)" to https://github.com/datastax/astrapy/blob/master/tests/astrapy/test_db.py shows that this test file does not exist.

Do you mean https://github.com/datastax/astrapy/blob/da549c34319d9ef33ceb2962d4445311b29da70f/scripts/astrapy_latest_interface.py?

**Comment by hemidactylus** [comment]
Thanks, The README is in dire need for maintenance indeed. Thank you for reporting.
