### ISSUE TITLE
Align function `collection.insert_one()`

### ISSUE THREAD

**Issue by clun** [datastax/astrapy#208]
#### Description
Make signature of insert_one() closer to pymongo

#### Informations
| Information | Value
| --------------|------------------|
| **Pymongo documentation** | [insert_one()](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.insert_one) |
| **Complexity points** | 8 |
| **Effort Size Estimation** | M |

#### Statement of work
- Create an object `InsertOneResult`to access outputs of the service
- The object will not have the `acknowledged` as not relevant for Astra
- The object will have the E
- Provide sample codes for passing and non-passing code (empty document, id already exist, not well formatted json.....) 
   - as a unit test
   - [in the official documentation](https://docs.datastax.com/en/astra/astra-db-vector/clients/python.html#insert-a-single-document)
- `ObjectID` does not exist in the Data Api world let us keep is a String `_id`

####  Data API Requests:
- _Request_
```json
{
  "insertOne": {
    "document": {
      "product_price": 9.99,
      "_id": "4cb3f1c3-b120-4e88-8ca3-87e624dc4348"
    }
  }
}
```
- _Response-OK_
```json
{"status":{"insertedIds":["4cb3f1c3-b120-4e88-8ca3-87e624dc4348"]}}
```
- _Reponse-KO_
```json
{"status":{"insertedIds":[]},"errors":[{"message":"Failed to insert document with _id 'p1': Document already exists with the given _id","errorCode":"DOCUMENT_ALREADY_EXISTS"}]}
```

### Expecting Working code

```python
result = db.test.insert_one({'x': 1})
result.inserted_id
```

**Comment by hemidactylus** [comment]
done (docs effort partially shifted elsewhere, also _id has changed since)
