### ISSUE TITLE
Align function `collection.insert_many`()

### ISSUE THREAD

**Issue by clun** [datastax/astrapy#209]
#### Description
Make signature of `insert_many()` closer to pymongo

#### Informations
| Information | Value
| --------------|------------------|
| **Pymongo documentation** | [insert_many()](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.insert_many) |
| **Complexity points** | 8 |
| **Effort Size Estimation** | M |

#### Statement of work
- Create an object `InsertManyResult`to access outputs of the service
- The object will not have the `acknowledged` as not relevant for Astra
- The object will have the E
- Provide sample codes for passing and non-passing code (empty document, id already exist, not well formatted json.....) 
   - as a unit test
   - in the official python reference documentation
- `ObjectID` does not exist in the Data Api world let us keep is a String `_id`
- If the amount of documents is too high, explicitly as the user to use chunked_insert_many()

####  Data API Requests:
- _Request_
```json
{
  "insertMany": {
    "documents": [
      {
        "firstName": "Lucas",
        "lastName": "Hernandez",
        "_id": "1"
      },
      {
        "firstName": "Antoine",
        "lastName": "Griezmann",
        "_id": "2"
      }
    ],
    "options": {
      "ordered": false
    }
  }
}
```
- _Response-OK_
```json
{
  "status": {
    "insertedIds": [
      "1",
      "2"
    ]
  }
}
```
- _Reponse-KO_ 1
```json
{"errors":[{"message":"Request invalid, the field postCommand.command.documents not valid: amount of documents to insert is over the max limit (24 vs 20).","exceptionClass":"ConstraintViolationException"}]}
```

- _Reponse-KO_ 2
```
{
  "status": {
    "insertedIds": []
  },
  "errors": [
    {
      "message": "Failed to insert document with _id '1': Document already exists with the given _id",
      "errorCode": "DOCUMENT_ALREADY_EXISTS"
    },
    {
      "message": "Failed to insert document with _id '2': Document already exists with the given _id",
      "errorCode": "DOCUMENT_ALREADY_EXISTS"
    }
  ]
}
```

### Expecting Working code

```python
result = db.insert_many([{'x': i} for i in range(2)])
result.inserted_ids
```

**Comment by hemidactylus** [comment]
done. return type brought to be more pymongo-like
