### ISSUE TITLE
Final init/auth params naming

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#21]
Suggestion: `db_id` => `database_id` everywhere.

Also (check with a broader set of folks) `token` => `api_key` (that was being discussed at length)

**Comment by erichare** [comment]
@clun just want to confirm that you agree with these two changes as well. I think it makes sense!

**Comment by hemidactylus** [comment]
Latest is:

1. `api_key` (a rename of `token`)
2. `api_endpoint` replacing region and db_id in regular flow (with builders, helpers and/or alternative signatures for nonstandard cases possibly)

**Comment by erichare** [comment]
Closing this issue as this has been merged in.
