### ISSUE TITLE
Align function `collection.update_one`

### ISSUE THREAD

**Issue by clun** [datastax/astrapy#211]
#### Description
Make signature of `update_one()` closer to pymongo

#### Informations
| Information | Value
| --------------|------------------|
| **Pymongo documentation** | [update_one()](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.update_one) |
| **Complexity points** | 8 |
| **Effort Size Estimation** | M |

#### Statement of work

- Adap signature to have filter, update and upsert at first level

```python
def update_one(filter, update, upsert)
```

- Create (or reuse) object `UpdateResult` for the output of the service.
- Provide sample codes for passing and non-passing code (empty document, not well formatted json.....) 
   - as a unit test
   - in the official documentationdocument

```json
{"updateOne":{"filter":{"a":"a"},"options":{"upsert":true},"update":{"$set":{"a":"b"}}}}
```
- _Response-OK_
```json
{"status":{"matchedCount":1,"modifiedCount":1}}
```

### Expecting Working code

```python
result = db.test.update_one({'x': 1}, {'$inc': {'x': 3}})
result.matched_count
```

**Comment by hemidactylus** [comment]
done
