### ISSUE TITLE
Align function `collection.update_many()`

### ISSUE THREAD

**Issue by clun** [datastax/astrapy#213]
#### Description
Make signature of `update_many()` closer to pymongo

#### Informations
| Information | Value
| --------------|------------------|
| **Pymongo documentation** | [update_many()](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.update_many) |
| **Complexity points** | 8 |
| **Effort Size Estimation** | M |

#### Statement of work
- Create or reuse UpdateResult with the matched_count, modified_count, upserted_id attributes
- Provide sample codes for passing and non-passing code
   - as a unit test
   - in the official python reference documentation

####  Data API Requests:
- _Request_
```json
---
```
- _Response-OK_
```json
{
  "status": {
    "insertedIds": [
      "1",
      "2"
    ]
  }
}
```
- _Reponse-KO_ 1
```json
---
```

- _Reponse-KO_ 2
```
---
```

### Expecting Working code

```python
result = db.update_many()
result.inserted_ids
```

**Comment by hemidactylus** [comment]
done
