### ISSUE TITLE
error handling after each API call

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#22]
Check each API response for the right shape (perhaps with automation to define the expected ok-shape)
and raise a verbose error if not

e.g. create collection currently can silently fail if 50 indexes (free tier)

**Comment by erichare** [comment]
I pushed an initial version of this, which at least logs and returns the error, but i'm keeping this open because checks on the return format are not there yet.

**Comment by hemidactylus** [comment]
There is another point to agree on:

_Do we want the methods in astrapy to raise an error if the HTTP method works all right but it contains information about a failure?_
Suppose my LLM Framework integration wants to create a collection. Would you like to have to inspect the response of astrapy's `create_collection` call, or would you rather have astrapy check its response and issue an error if the intent of the create collection does not succeed?
I realize the SDK could just, you know, be a proxy for http methods, but it could also act as the natural point for raising exceptions perhaps (?) though I'm not 100% sure of that (there are grey areas ... what about insertMany that fails halfway through, for instance? Hmm)

**Comment by hemidactylus** [comment]
@erichare as per our meeting, this could be reassigned to Kirsten (i.e. @synedra as far as I know)

**Comment by erichare** [comment]
I think when @synedra accepts the invite from cedrick we'll be able to re-assign. I unassigned myself for now!

**Comment by synedra** [comment]
I found the message, clicked on it, and then it disappeared without letting me accept the invite :-(

Kirsten
