### ISSUE TITLE
Remove the vector and vectorize parameters for insertMany etc

### ISSUE THREAD

**Issue by amorton** [datastax/astrapy#281]
For example here https://github.com/datastax/astrapy/blob/cb881ee4ed8b104002421a2665920789553821df/astrapy/operations.py#L163-L164

The vector and vecotrize are part of the document, it is confusing to be able to specify them in two locations. And the different name has already lead to confusion with users not know what name to use `vectorize` or `$vectorize`. 

Finally, this means the client API does not reflect the way server side API works as we want to avoid that. 

Can we remove the params from the python, JS and Java clients please.

**Comment by hemidactylus** [comment]
will start deprecation in 1.3 and removal is scheduled for 2.0
