### ISSUE TITLE
allow empty or null filter in delete_many call

### ISSUE THREAD

**Issue by amorton** [datastax/astrapy#282]
from here https://github.com/datastax/astrapy/blob/cb881ee4ed8b104002421a2665920789553821df/astrapy/collection.py#L2223

The server allows an empty filter to truncate the table, there is no reason for the client stop that. 

it is also expected behaviour from other document databases. 

Can we remove this check in the python, JS, and Java clients please.

**Comment by hemidactylus** [comment]
merged, ready to get out with 1.3
