### ISSUE TITLE
More flexible test fixtures for single-method testing

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#47]
The db and collection are independent fixtures right now, which makes it hard to e.g. select a single test method because it may happen that the collection is not created or similar (e.g. test_collection with `-k test_insert_many` or similar).

Make fixtures module-scoped and perhaps nest them or something, so that each method runs by itself all right
(also do not assume any order between test function calls)

**Comment by erichare** [comment]
See #56

**Comment by erichare** [comment]
Merged in, closing as completed (though of course there will be ongoing work to improve the tests!)
