### ISSUE TITLE
Offer full support for customized/ non-prod DevOps API URL root

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#49]
General problem: `assuming prod in the devops API (url)` vs `keeping it simple for the happy path of prod usage`.

Idea from a conversation:

There is no way to "spawn" a DBOps object from the general AstraDB. _If there were one_, then I would tell you:
> regular usage would have users "spawn" an Ops from their main `AstraDB` instance, which would have an `.ops()` method spawning an `AstraDBOps`. That method would sound like this:

```(in the AstraDB class)

  def ops(self, dev_ops_url=None):
    if dev_ops_url is None and self.base_url = <production api url>:
        dev_ops_url = <prod OPS url>
   return AstraDBOps(self.api_key, dev_ops_url=dev_ops_url)```

**Comment by erichare** [comment]
#48 should address this i hope, let me know @hemidactylus
