### ISSUE TITLE
Improve error handling for requests

### ISSUE THREAD

**Issue by hemidactylus** [datastax/astrapy#59]
Errors in the requests.request method in `utils.py` do not work as intended: the try/except block there makes the `make_request` method return a JSON instead of a request object, so that callers (such as `_request` of AstraDBCollection) fail when they try the `.json()` method on these.

I just saw this thanks to someAstra API hiccup:

```
    create_collection_response = self.astra_db.create_collection(
  File "[...]/astrapy/db.py", line 360, in create_collection
    response = self._request(
  File "[...]/astrapy/db.py", line 329, in _request
    responsebody = response.json()
AttributeError: 'dict' object has no attribute 'json'
```

Option 1: remove the try/except altogether in make_request. Onus is on the client.

Option 2:
- `make_request` returns the request.json() when this works, otherwise returns `{"errors": [...]}`, ready to be used by the caller just like the errors genuinely coming from the API
- callers would do something like `responsebody = make_request(...)` and call it a day
- *Except*: the DevOps case, which also uses make_request, is different - that one is based on http status codes and headers, the response being the empty string. Perhaps the safest thing is a flag to make_request behave as required there?

**Comment by erichare** [comment]
You know, my personal opinion is that it's better that we NOT have the try/except block - let the API return what the API returns. Putting the onus on the client i think actually makes the most sense from an API design perspective. We can post process errors in some way, but we shouldn't just treat some api call failure as something we can catch in an except block.
