### ISSUE TITLE
Connection example when connecting to K8ssandra

### ISSUE THREAD

**Issue by echarles** [datastax/astrapy#6]
The current example on the README assume the developer connects to AstraDB.

I would be nice to also have example to connect to plain cassandra deployed by K8ssandra.

Or maybe this is not in the goal of this library? The name `astrapy` looks like it is targeted at AstraDB?

**Comment by kidrecursive** [comment]
Heya, yes, currently it is target at Astra DB. However, I am adding local Stargate support shortly and will add an example in the README. Thanks!

**Comment by clun** [comment]
Thank you for the ticket !

**Comment by kidrecursive** [comment]
Heya, I modified things so that you should be able to specify the stargate connection. The release is 0.3.2: https://github.com/datastax/astrapy#connecting-to-a-local-stargate-instance

Thanks!

**Comment by echarles** [comment]
@kidrecursive Awesome. Let me try that my tomorrow and give you feedback

**Comment by echarles** [comment]
@kidrecursive I get an error `create_astra_client() got an unexpected keyword argument 'base_auth_url'`

```py
>>> import os
>>> from astrapy.client import create_astra_client
stargate_client = create_astra_client(
  base_url = "http://localhost:8082",
  base_auth_url = "http://localhost:8081/v1/auth",
  username = os.getenv('K8SSANDRA_USERNAME'),
  password = os.getenv('K8SSANDRA_PASSWORD'),
)
>>> stargate_client = create_astra_client(
...   base_url = "http://localhost:8082",
...   base_auth_url = "http://localhost:8081/v1/auth",
...   username = os.getenv('K8SSANDRA_USERNAME'),
...   password = os.getenv('K8SSANDRA_PASSWORD'),
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: create_astra_client() got an unexpected keyword argument 'base_auth_url'
```

```
p
ip list | grep astra
astrapy                           0.3.2
```

**Comment by kidrecursive** [comment]
Ah, typo in the readme, it's `auth_base_url`

**Comment by echarles** [comment]
Connection is now working. Thx @kidrecursive 👍
