### ISSUE TITLE
[core] Most JSON-y parameters have "null-like" defaults despite no API support

### ISSUE THREAD

**Issue by erichare** [datastax/astrapy#80]
Remove defaults, require the params be passed if required by API

**Comment by hemidactylus** [comment]
This is especially evident in `ops.py` which would need some love (and ample work in digging through the docs + challenging stuff for better testing)

**Comment by erichare** [comment]
@hemidactylus do you think this can now be closed in favor of the love to ops task, which of course requires a ton of work.... but with the db.py functions it seems we're in a much better spot than we were, and can maybe handle on a case by case basis?

**Comment by hemidactylus** [comment]
closing as core is being (slowly) abandoned in favour of "pure idiomatic"
